version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: AuthServiceChatter_postgres
    restart: always
    environment:
      POSTGRES_DB: Chatter
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data 

volumes:
  postgres_data: